#include <iostream>
using namespace std;
int main(){
    try{ throw 'a';    }catch(int param){
        cout<<"int exception n";
    }catch(int param){
        cout<<"int exception"; 
    }catch(...){
        cout<<"default exception n";
    }cout<<"After Exception ";
    return 0;
}
